BaseUrl = "http://railsbling.com"
LanguageCode = "en-us"
Title = "Rails Bling"
disqusShortname = "railsbling"

[params]
  author = "Peter Boling"
  AuthorName = "Peter Boling"
  DateForm = "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID = "UA-37606822-1"
  gaid = "UA-37606822-1"
  baseurl = "http://www.railsbling.com/"
  Facebook = "peter.boling"
  Twitter = "galtzo"
  Github = "pboling"
  ShowRelatedPost = true
  Disqus = "peterboling"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  sidebartitle = "Rails Bling"
  sidebartagline = "Yet Another Paradigm by Peter Boling"
  categoriescss = "/css/project.css"
  noauthor = false

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[[menu.main]]
    name = "Blog"
    url = "/posts"
[[menu.main]]
    name = "FOSS"
    url = "/foss"
[[menu.main]]
    name = "Resume"
    url = "/cv"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/pboling"
    identifier = "github"
[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/peterboling"
    identifier = "linkedin"
[[menu.social]]
    pre = "<i class='fa fa-diamond'></i>"
    url = "https://rubygems.org/profiles/pboling"
    identifier = "rubygems"
[[menu.social]]
    pre = "<i class='fa fa-angellist'></i>"
    url = "https://angel.co/peter-boling"
    identifier = "angellist"
[[menu.social]]
    pre = "<i class='fa fa-code-fork'></i>"
    url = "https://www.crunchbase.com/person/peter-boling#/entity"
    identifier = "crunchbase"
[[menu.social]]
    pre = "<i class='fa fa-smile-o'></i>"
    url = "https://about.me/peter.boling"
    identifier = "aboutme"
[[menu.social]]
    pre = "<i class='fa fa-code'></i>"
    url = "https://stackoverflow.com/users/213191/peter-h-boling?tab=profile"
    identifier = "stackoverflow"
[[menu.social]]
    pre = "<i class='fa fa-trophy'></i>"
    url = "http://github-awards.com/users/search?login=pboling"
    identifier = "awards"
[[menu.social]]
    pre = "<i class='fa fa-cogs'></i>"
    url = "https://coderbits.com/pboling"
    identifier = "coderbits"
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/galtzo"
    identifier = "twitter"
[[menu.social]]
    pre = "<i class='fa fa-facebook'></i>"
    url = "https://www.facebook.com/peter.boling"
    identifier = "facebook"
[[menu.social]]
    pre = "<i class='fa fa-google-plus'></i>"
    url = "https://plus.google.com/+PeterBoling/posts"
    identifier = "google-plus"
[[menu.social]]
    pre = "<i class='fa fa-gittip'></i>"
    url = "https://gratipay.com/~pboling/"
    identifier = "gittip"

[[menu.footer]]
    name = "My Old Blog"
    url = "http://galtzo.blogspot.com"
