BaseUrl = "http://railsbling.com"
LanguageCode = "en-us"
Title = "Rails Bling"

[params]
  author = "Peter Boling"
  AuthorName = "Peter Boling"
  DateForm = "Mon, Jan 2, 2006"
  GoogleAnalyticsUserID = "UA-37606822-1"
  Facebook = "peter.boling"
  Twitter = "galtzo"
  Github = "pboling"
  ShowRelatedPost = true
  Disqus = "peterboling"
  SyntaxHighlightTheme = "solarized_dark.min.css"
  sidebartitle = "Rails Bling"
  sidebartagline = "Yet Another Paradigm by Peter Boling"

[permalinks]
    post = "/blog/:year/:month/:day/:title/"

[[menu.social]]
    pre = "<i class='fa fa-github'></i>"
    url = "https://github.com/pboling"
    identifier = "github"
[[menu.social]]
    pre = "<i class='fa fa-twitter'></i>"
    url = "https://www.twitter.com/galtzo"
    identifier = "twitter"
[[menu.social]]
    pre = "<i class='fa fa-facebook'></i>"
    url = "https://www.facebook.com/peter.boling"
    identifier = "facebook"
[[menu.social]]
    pre = "<i class='fa fa-linkedin'></i>"
    url = "https://www.linkedin.com/in/peterboling"
    identifier = "linkedin"
