name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 * * *'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Make it new
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo -D

      - name: SFTP uploader w/options
        uses: zurb/sftp-upload-action@1.3
        with:
          host: railsbling.com
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'public/'
          remoteDir: '/home/${{ secrets.FTP_USERNAME }}/railsbling.com/'
          dryRun: false
          excludeMode: 'remove'
  #        exclude: "[                     // exclude patterns (glob)
  #          'node_modules',
  #          'src/**/*.spec.ts'
  #        ]",                              // Optional. Default to [].
          concurrency: 100                 // Optional. Default to 100.

