name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 * * *'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    name: Make it new
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo -D

      - name: SFTP Upload
        id: upload
        uses: Creepios/sftp-action@v1.0.3
        with:
          host: railsbling.com
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localPath: public/
          remotePath: /home/${{ secrets.FTP_USERNAME }}/railsbling.com/
