name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 8 * * *'
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo -D

      - name: SFTP uploader
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: railsbling.com
          port: 22
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: public/
          remoteDir: /home/${{ secrets.FTP_USERNAME }}/railsbling.com/
          dryRun: false
